2025-01-22 18:20:09,543 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\novik\PycharmProjects\PythonProject\module_12\tests_12_4.py", line 23, in test_run
    runner = Runner(True)
  File "C:\Users\novik\PycharmProjects\PythonProject\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool
2025-01-22 18:20:09,546 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\novik\PycharmProjects\PythonProject\module_12\tests_12_4.py", line 13, in test_walk
    wolker = Runner('Тихоня', -4)
             ~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\novik\PycharmProjects\PythonProject\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -4
